# config.py

import os

COLOR_CPU = '#FF4B4B'
COLOR_CPU_TEMP = '#FFD700'
COLOR_MEM = '#0068C9'
COLOR_SWAP = '#FFA500'
COLOR_PROCESS = '#800080'
COLOR_ANOMALY = 'rgba(255, 0, 0, 0.1)'
COLOR_INSPECTOR_FRAME = '#6A4C93'
COLOR_INSPECTOR_TOTAL = '#FF9F1C'
COLOR_INSPECTOR_MEM = '#2A9D8F'

DEFAULT_LOG_DIR = r"C:\SystemLogs"

LAST_BUILD = "~0,4datetime:~4,2datetime:~6,2datetime:~8,2datetime:~10,2" # Updated by build.bat

# Collector Settings
SAMPLE_INTERVAL_SEC = 1
AGGREGATION_WINDOW_SEC = 5
TOP_N = 5
OUTPUT_DIR = DEFAULT_LOG_DIR
ENABLE_SUMMARY_LOG = True
CSV_ENCODING = 'utf-8-sig'

ARTIFACT_ROOT_DIR = ".artifacts"
MANUAL_SITE_DIR = os.path.join(ARTIFACT_ROOT_DIR, "manual-site")
RELEASE_ROOT_DIR = os.path.join(ARTIFACT_ROOT_DIR, "releases")

