# data_loader.py
import pandas as pd
import streamlit as st
import os

def _is_parquet_cache_valid(csv_path, parquet_path):
    if not (os.path.exists(csv_path) and os.path.exists(parquet_path)):
        return False
    return os.path.getmtime(parquet_path) >= os.path.getmtime(csv_path)

def _downcast_numeric(df):
    float_cols = df.select_dtypes(include=['float64']).columns
    int_cols = df.select_dtypes(include=['int64']).columns

    for col in float_cols:
        df[col] = pd.to_numeric(df[col], downcast='float')
    for col in int_cols:
        df[col] = pd.to_numeric(df[col], downcast='integer')
    return df

@st.cache_data
def load_data(files):
    """
    Loads data using the new format generated by the Python collector.
    Performs an exact merge on 'Timestamp' between resource and process datasets.
    """
    import concurrent.futures
    
    resource_dfs = []
    process_dfs = []
    
    max_workers = min(8, max(1, len(files)))
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        results = executor.map(process_single_file, files)
        
    for res in results:
        if res is None: continue
        rtype, df = res
        
        if rtype == 'resource':
            resource_dfs.append(df)
        elif rtype == 'process':
            process_dfs.append(df)

    res_df = None
    if resource_dfs:
        res_df = pd.concat(resource_dfs, ignore_index=True)
        res_df = res_df.dropna(subset=['Timestamp']).sort_values('Timestamp')
        
    proc_df = None
    if process_dfs:
        proc_df = pd.concat(process_dfs, ignore_index=True)
        proc_df = proc_df.dropna(subset=['Timestamp']).sort_values('Timestamp')

    if res_df is not None and proc_df is not None:
        # Exact merge since both are generated on the exact same 5s boundary
        merged = pd.merge(res_df, proc_df, on='Timestamp', how='outer', suffixes=('', '_proc'))
        return _downcast_numeric(merged)
    elif res_df is not None:
        return _downcast_numeric(res_df)
    elif proc_df is not None:
        return _downcast_numeric(proc_df)
        
    return None

def _clean_column_names(df):
    import re
    def _clean(c):
        if not isinstance(c, str): return c
        c = c.replace('\x00', '')
        m = re.search(r'_(.*?)([A-Z]:(?:,[A-Z]:)*|PhysicalDrive\d+)(.*?)\(', c)
        if m and ('DiskTime_' in c or 'DiskRead_' in c or 'DiskWrite_' in c) and '(' in c:
            base = c.split('_')[0]
            unit = '(' + c.split('(')[1]
            drive = m.group(2)
            return f"{base}_{drive}{unit}"
        return c
    df.columns = [_clean(c) for c in df.columns]
    return df

def process_single_file(f):
    try:
        is_local_file = isinstance(f, str)
        fname = f if is_local_file else f.name
        
        if is_local_file:
            parquet_path = f.replace('.csv', '.parquet')
            if _is_parquet_cache_valid(f, parquet_path):
                try:
                    df = pd.read_parquet(parquet_path)
                    rtype = 'resource' if 'CPU_Avg(%)' in df.columns else 'process'
                    return (rtype, _clean_column_names(df))
                except:
                    pass

        try:
            df = pd.read_csv(f, engine='pyarrow')
        except:
            df = pd.read_csv(f, low_memory=False)
            
        # Parse Timestamp
        if 'Timestamp' in df.columns:
            df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce').astype('datetime64[ns]')
            
        # Determine format structurally rather than relying entirely on filename
        # Though files are named resource_*.csv and process_*.csv
        if 'CPU_Avg(%)' in df.columns:
            rtype = 'resource'
            # Legacy dashboards may look for 'CPU(%)', 'Used(GB)', 'Usage(%)'
            # Mapping canonical names to what old dashboard logic expects if possible,
            # or we just update the dashboard. Updating dashboard is better.
        elif 'Top5_CPU(%)' in df.columns:
            rtype = 'process'
        else:
            return None # Ignore unrecognized CSVs
            
        df = _downcast_numeric(df)
        df = _clean_column_names(df)
        
        if is_local_file:
            try:
                df.to_parquet(parquet_path, index=False)
            except:
                pass

        return (rtype, df)
        
    except Exception as e:
        return None
